# @package _global_

defaults:
- override /policy: vos_3d_robot_masked_transformer_policy
- override /policy/data_augmentation@policy.pcd_aug: se3_augmentation_3
- override /train/scheduler: cosine_annealing_warm_restarts
benchmark_name: VOS_3D_Ablation_Augmentation_Benchmark
data:
  obs:
    modality:
      grouped_pcd: [neighborhood_10_64, centers_10_64]
      low_dim: [gripper_states, joint_states]
      normalized_pcd: [xyz]
      pcd: []
      wrist_depth: [eye_in_hand_depth]
  use_joint: true
experiment_description: ''
policy:
  pcd_aug:
    network_kwargs:
      enabled: true
      mean: 0.0
      rot_range: [0.0, 0.0, 0.0]
      std: 0.001
      use_position: true
      use_rotation: false
  pcd_encoder:
    network_kwargs:
      group_cfg: {group_size: 64, num_group: 10}
task_id: 3
train: {grad_clip: 100.0, n_epochs: 100}
