# @package _global_

defaults:
- override /policy: bc_real_robot_rnn_rgbd_policy
- override /train/scheduler: cosine_annealing_warm_restarts


benchmark_name:  VOS_3D_Real_Robot_RGBD_Benchmark

task_id: 6

train:
  grad_clip: 100.
  n_epochs: 100
  # batch_size: 64

data:
  obs:
    modality:
      pcd: []
      low_dim: ["gripper_states", "joint_states"]
      rgb: ["agentview_rgb"]
      real_depth: ["agentview_depth"]

  use_joint: true

experiment_description: "BC-RNN Baseline"