# @package _global_

defaults:
- override /policy: GROOT_robot_masked_transformer_policy
- override /policy/data_augmentation@policy.pcd_aug: se3_augmentation_3
- override /train/scheduler: cosine_annealing_warm_restarts

benchmark_name: GROOT_Real_Robot_Benchmark

task_id: 0

policy:
  pcd_aug:
    network_kwargs:
      mean: 0.0
      std: 0.001
      use_position: True
      enabled: True
      use_rotation: False
      rot_range: [0.0, 0.0, 0.0]
  pcd_encoder:
    network_kwargs:
        group_cfg:
          num_group: 10
          group_size: 64

train:
  grad_clip: 100.
  n_epochs: 100
  # batch_size: 64

data:
  obs:
    modality:
      pcd: []
      normalized_pcd: ["xyz"]
      wrist_depth: ["eye_in_hand_depth"]
      low_dim: ["gripper_states", "joint_states"]
      grouped_pcd: ["neighborhood_10_64", "centers_10_64"]

  use_joint: true

experiment_description: ""