# @package _global_

defaults:
- override /policy: groot_masked_transformer_policy
- override /policy/data_augmentation@policy.pcd_aug: se3_augmentation_3
- override /train/scheduler: cosine_annealing_warm_restarts


task_id: 2

policy:
  pcd_aug:
    network_kwargs:
      mean: 0.0
      std: 0.002
      use_position: True
      enabled: True
      use_rotation: False
      rot_range: [0.0, 0.0, 0.0]

train:
  grad_clip: 100.
  n_epochs: 100

data:
  obs:
    modality:
      pcd: []
      normalized_pcd: ["xyz"]
      wrist_depth: ["eye_in_hand_depth"]
      low_dim: ["gripper_states", "joint_states"]

  use_joint: true