# @package _global_

defaults:
  - _self_
  - data: default
  - datasets: default
  - policy: groot_real_robot_no_wrist_transformer_policy
  - train: default
  - eval: default
  - lifelong: groot_single_task
  - real_robot_experiments: null
  - test: null

seed: 10000
use_wandb: false
wandb_project: "lifelong learning"
folder: null # use default path
bddl_folder: null # use default path
init_states_folder: null # use default path
load_previous_model: false
device: "cuda"
task_embedding_format: "bert"
task_embedding_one_hot_offset: 1
pretrain: false
pretrain_model_path: ""
benchmark_name: "GROOT_Real_Robot_Benchmark"
task_id: 0


dataset_path: null
save_video: true

vos_annotation: true
object_pcd: true
pcd_aug: true
pcd_grouping: true
delete_intermediate_files: true
