# @package _global_

defaults:
- override /policy: bc_mae_policy
- override /train/scheduler: cosine_annealing_warm_restarts
benchmark_name: VOS_3D_Simulation_RGBD_Benchmark
data:
  obs:
    modality:
      pcd: []
      wrist_depth: ["eye_in_hand_depth"]
      low_dim: ["gripper_states", "joint_states"]
      rgb: ["agentview_rgb"]
      depth: ["agentview_depth"]

  use_joint: true
experiment_description: ''
policy:
  pcd_aug:
    network_kwargs:
      enabled: true
      mean: 0.0
      rot_range: [0.0, 0.0, 0.0]
      std: 0.001
      use_position: true
      use_rotation: false

task_id: 0
train: {grad_clip: 100.0, n_epochs: 100}
